apiVersion: v1
kind: PersistentVolume
metadata: 
  labels: 
    type: local
  name: mysql-pv-volume
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 10Gi
  hostPath: 
    path: /mnt/data
  storageClassName: manual
